/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.xtext.example.mydsl.idea.completion.AbstractMyDslCompletionContributor;
import org.xtext.example.mydsl.idea.lang.MyDslLanguage;

@SuppressWarnings("all")
public class MyDslCompletionContributor extends AbstractMyDslCompletionContributor {
  public MyDslCompletionContributor() {
    this(MyDslLanguage.INSTANCE);
  }
  
  public MyDslCompletionContributor(final AbstractXtextLanguage lang) {
    super(lang);
  }
}
