/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.quickfix;

import org.eclipse.xtext.example.fowlerdsl.validation.StatemachineValidator;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class StatemachineQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(StatemachineValidator.INVALID_NAME)
  public void capitalizeName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method get(Integer, int) is undefined for the type IXtextDocument"
      + "\nThe method replace(Integer, int, Object) is undefined for the type IXtextDocument"
      + "\ntoLowerCase cannot be resolved");
  }
}
