/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.xtext.example.fowlerdsl.statemachine.State;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class StatemachineLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public StatemachineLabelProvider(final /* org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider */Object delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nInvalid number of arguments. The constructor DefaultEObjectLabelProvider() is not applicable for the arguments (AdapterFactoryLabelProvider)");
  }
  
  public String text(final State state) {
    String _name = state.getName();
    return ("state " + _name);
  }
}
