/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.idea;

import org.xtext.example.mydsl.idea.AbstractMyDslIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class MyDslIdeaModule extends AbstractMyDslIdeaModule {
}
