/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries;
import org.xtext.example.mydsl.idea.MyDslStandaloneSetupIdea;

@SuppressWarnings("all")
public class MyDslIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    Injector _xblockexpression = null;
    {
      EcoreGlobalRegistries.ensureInitialized();
      MyDslStandaloneSetupIdea _myDslStandaloneSetupIdea = new MyDslStandaloneSetupIdea();
      _xblockexpression = _myDslStandaloneSetupIdea.createInjector();
    }
    return _xblockexpression;
  }
}
