/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class MyDslIdeaModule extends AbstractMyDslIdeaModule {
}
