/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.idea.lang;

import org.xtext.example.mydsl.idea.lang.AbstractMyDslFileType;
import org.xtext.example.mydsl.idea.lang.MyDslLanguage;

@SuppressWarnings("all")
public class MyDslFileType extends AbstractMyDslFileType {
  public final static MyDslFileType INSTANCE = new MyDslFileType();
  
  public MyDslFileType() {
    super(MyDslLanguage.INSTANCE);
  }
}
