/**
 * Generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.web.contentassist;

import org.eclipse.xtext.example.fowlerdsl.web.contentassist.AbstractStatemachineProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StatemachineProposalProvider extends AbstractStatemachineProposalProvider {
}
